---
- name: Install elastalert
  hosts: "{{ target }}"
  gather_facts: True
  become: true

  pre_tasks:
    - name: create elastalert group
      group: name="{{ elastalert_group }}" state=present

    - name: create elastic user
      user: name="{{ elastalert_user }}" shell=/bin/bash groups="{{ elastalert_group }}" append=yes

  roles:
    # - oracle-jdk
    - elastalert
